import { Role } from 'src/enums/role.enum';

export const Permissions = {
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  USERS_MANAGE: 'users.manage',
  USERS_VIEW: 'users.view',
  USERS_ASSIGN_ROLES: 'users.assign_roles',

  ROLES_CREATE: 'roles.create',
  ROLES_VIEW: 'roles.view',
  ROLES_UPDATE: 'roles.update',
  ROLES_DELETE: 'roles.delete',
  ROLES_ASSIGN_PERMISSIONS: 'roles.assign_permissions',

  PERMISSIONS_CREATE: 'permissions.create',
  PERMISSIONS_VIEW: 'permissions.view',

  TEAMS_CREATE: 'teams.create',
  TEAMS_VIEW: 'teams.view',
  TEAMS_VIEW_ALL: 'teams.view.all',
  TEAMS_UPDATE: 'teams.update',
  TEAMS_DELETE: 'teams.delete',
  TEAMS_MANAGE: 'teams.manage',

  PROJECTS_CREATE: 'projects.create',
  PROJECTS_VIEW: 'projects.view',
  PROJECTS_VIEW_ALL: 'projects.view.all',
  PROJECTS_UPDATE: 'projects.update',
  PROJECTS_DELETE: 'projects.delete',

  TASKS_CREATE: 'tasks.create',
  TASKS_VIEW: 'tasks.view',
  TASKS_VIEW_ALL: 'tasks.view.all',
  TASKS_ASSIGN: 'tasks.assign',
  TASKS_UPDATE: 'tasks.update',
  TASKS_DELETE: 'tasks.delete',
  TASKS_TEST_UPDATE: 'tasks.test_update',
  TASK_TEST: 'tasks.test_task',
  REPORT_BUG: 'tasks.report_bug',
  VERIFY_TASK: 'tasks.verify_task',

  COMMENTS_CREATE: 'comments.create',
  COMMENTS_VIEW: 'comments.view',
  COMMENTS_DELETE: 'comments.delete',

  ATTACHMENTS_UPLOAD: 'attachments.upload',
  ATTACHMENTS_VIEW: 'attachments.view',
  ATTACHMENTS_DELETE: 'attachments.delete',

  NOTIFICATIONS_VIEW: 'notifications.view',

  REPORTS_VIEW: 'reports.view',

  CREATE_PROJECT: 'projects.create',
  UPDATE_PROJECT: 'projects.update',
  DELETE_PROJECT: 'projects.delete',
  VIEW_PROJECT: 'projects.view',
  CREATE_TASK: 'tasks.create',
  ASSIGN_TASK: 'tasks.assign',
  UPDATE_TASK: 'tasks.update',
  DELETE_TASK: 'tasks.delete',
  VIEW_TASK: 'tasks.view',
  TEST_TASK: 'tasks.test_task',
  MANAGE_TEAM: 'teams.manage',
  MANAGE_USERS: 'users.manage',
  ASSIGN_ROLE: 'users.assign_roles',
  VIEW_REPORTS: 'reports.view',
  USER_CREATE: 'users.create',
  USER_UPDATE: 'users.update',
  USER_DELETE: 'users.delete',
  USER_MANAGE: 'users.manage',
  ROLE_CREATE: 'roles.create',
  ROLE_ASSIGN: 'users.assign_roles',
  ROLE_MANAGE: 'roles.update',
  PERMISSION_MANAGE: 'permissions.create',
  REPORT_VIEW: 'reports.view',
  SYSTEM_MANAGE: 'system.manage',
  TEAM_CREATE: 'teams.create',
  PROJECT_VIEW_ALL: 'projects.view',
  PROJECT_CREATE: 'projects.create',
  PROJECT_UPDATE: 'projects.update',
  TASK_CREATE: 'tasks.create',
  TASK_ASSIGN: 'tasks.assign',
  TASK_MONITOR: 'tasks.view',
  TEAM_PERFORMANCE_VIEW: 'reports.view',
  PROJECT_VIEW: 'projects.view',
  TASK_VIEW: 'tasks.view',
  BUG_REPORT: 'tasks.report_bug',
  BUG_VERIFY: 'tasks.verify_task',
  COMMENT_CREATE: 'comments.create',
  TASK_VIEW_ASSIGNED: 'tasks.view',
  TASK_UPDATE_PERCENTAGE: 'tasks.update',
  TASK_MARK_STARTED: 'tasks.update',
  TASK_MARK_COMPLETED: 'tasks.update',
  VIEW_DASHBOARD: 'reports.view',
} as const;

export type Permission = (typeof Permissions)[keyof typeof Permissions];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [Role.SUPER_ADMIN]: Array.from(new Set(Object.values(Permissions))),
  [Role.ADMIN]: [
    Permissions.USERS_MANAGE,
    Permissions.USERS_CREATE,
    Permissions.USERS_UPDATE,
    Permissions.USERS_DELETE,
    // Permissions.USERS_ASSIGN_ROLES,
    // Permissions.ROLES_CREATE,
    // Permissions.ROLES_VIEW,
    // Permissions.ROLES_UPDATE,
    // Permissions.ROLES_DELETE,
    // Permissions.ROLES_ASSIGN_PERMISSIONS,
    // Permissions.PERMISSIONS_CREATE,
    // Permissions.PERMISSIONS_VIEW,
    Permissions.TEAMS_MANAGE,
    Permissions.TEAMS_VIEW_ALL,
    Permissions.PROJECTS_CREATE,
    Permissions.PROJECTS_VIEW,
    Permissions.PROJECTS_VIEW_ALL,
    Permissions.PROJECTS_UPDATE,
    Permissions.PROJECTS_DELETE,
    Permissions.TASKS_CREATE,
    Permissions.TASKS_ASSIGN,
    Permissions.TASKS_VIEW,
    Permissions.TASKS_VIEW_ALL,
    Permissions.TASKS_UPDATE,
    Permissions.TASKS_DELETE,
    Permissions.TASKS_TEST_UPDATE,
    Permissions.TEST_TASK,
    Permissions.REPORT_BUG,
    Permissions.VERIFY_TASK,
    Permissions.COMMENTS_CREATE,
    Permissions.COMMENTS_VIEW,
    Permissions.COMMENTS_DELETE,
    Permissions.ATTACHMENTS_UPLOAD,
    Permissions.ATTACHMENTS_VIEW,
    Permissions.ATTACHMENTS_DELETE,
    Permissions.REPORTS_VIEW,
    Permissions.NOTIFICATIONS_VIEW,
  ],
  [Role.PROJECT_MANAGER]: [
    Permissions.USERS_VIEW,
    Permissions.TEAMS_VIEW,
    Permissions.PROJECTS_CREATE,
    Permissions.PROJECTS_VIEW,
    Permissions.PROJECTS_UPDATE,
    Permissions.TASKS_CREATE,
    Permissions.TASKS_ASSIGN,
    Permissions.TASKS_VIEW,
    Permissions.TASKS_UPDATE,
    Permissions.COMMENTS_CREATE,
    Permissions.COMMENTS_VIEW,
    Permissions.COMMENTS_DELETE,
    Permissions.ATTACHMENTS_UPLOAD,
    Permissions.ATTACHMENTS_VIEW,
    Permissions.ATTACHMENTS_DELETE,
    Permissions.REPORTS_VIEW,
    Permissions.NOTIFICATIONS_VIEW,
  ],
  [Role.TESTER]: [
    Permissions.TEAMS_VIEW,
    Permissions.PROJECTS_VIEW,
    Permissions.TASKS_VIEW,
    Permissions.TASKS_TEST_UPDATE,
    Permissions.TEST_TASK,
    Permissions.REPORT_BUG,
    Permissions.VERIFY_TASK,
    Permissions.COMMENTS_CREATE,
    Permissions.COMMENTS_VIEW,
    Permissions.ATTACHMENTS_UPLOAD,
    Permissions.ATTACHMENTS_VIEW,
    Permissions.REPORTS_VIEW,
    Permissions.NOTIFICATIONS_VIEW,
  ],
  [Role.TEAM_MEMBER]: [
    Permissions.TEAMS_VIEW,
    Permissions.PROJECTS_VIEW,
    Permissions.TASKS_VIEW,
    Permissions.TASKS_UPDATE,
    Permissions.COMMENTS_CREATE,
    Permissions.COMMENTS_VIEW,
    Permissions.ATTACHMENTS_UPLOAD,
    Permissions.ATTACHMENTS_VIEW,
    Permissions.NOTIFICATIONS_VIEW,
  ],
};
